function validate_drs_kers_setup()
%VALIDATE_DRS_KERS_SETUP Validate the distance-based DRS/KERS setup.
% This check does not require CasADi, the track MAT files, or an NLP solve.
%
% Important: the optimization implements a distance-based increase of the
% available rear-drivetrain power ceiling. It does not introduce a separate
% KERS-energy state or enforce the FIA 400 kJ/lap integral limit.

base_dir = fileparts(mfilename('fullpath'));
old_dir = pwd;
cleanup = onCleanup(@() cd(old_dir)); %#ok<NASGU>
cd(base_dir);

csv_file = 'rosberg_2012_china_distance_speed_drs_kers_1m(4).csv';
interval_file = 'rosberg_2012_china_drs_kers_active_intervals(3).csv';

assert(isfile(csv_file), 'validate_drs_kers:MissingCSV', ...
    'Required CSV is missing: %s', csv_file);

T = readtable(csv_file);
required = {'distance_official_length_scaled_m','drs_on', ...
    'kers_active','lap_time_s'};
assert(all(ismember(required, T.Properties.VariableNames)), ...
    'validate_drs_kers:InvalidCSV', ...
    ['CSV must contain distance_official_length_scaled_m, drs_on, ' ...
     'kers_active and lap_time_s.']);

distance_m = double(T.distance_official_length_scaled_m(:));
drs_on = double(T.drs_on(:));
kers_on = double(T.kers_active(:));
lap_time_s = double(T.lap_time_s(:));

assert(all(isfinite(distance_m)) && all(diff(distance_m) > 0), ...
    'validate_drs_kers:InvalidDistance', ...
    'Distance must be finite and strictly increasing.');
assert(all(isfinite(lap_time_s)) && all(diff(lap_time_s) >= 0), ...
    'validate_drs_kers:InvalidTime', ...
    'lap_time_s must be finite and non-decreasing.');
assert(all(ismember(drs_on, [0 1])), ...
    'validate_drs_kers:InvalidDRS', 'drs_on must be binary.');
assert(all(ismember(kers_on, [0 1])), ...
    'validate_drs_kers:InvalidKERS', 'kers_active must be binary.');

[drs_start, drs_end] = active_intervals(drs_on);
[kers_start, kers_end] = active_intervals(kers_on);
assert(numel(drs_start) == 7, 'validate_drs_kers:DRSCount', ...
    'Expected 7 Rosberg DRS-on intervals, found %d.', numel(drs_start));
assert(numel(kers_start) == 4, 'validate_drs_kers:KERSCount', ...
    'Expected 4 Rosberg KERS-on intervals, found %d.', numel(kers_start));

kers_last_on = zeros(size(kers_on));
kers_last_on(kers_start(end):kers_end(end)) = 1;
assert(all(kers_last_on <= kers_on), ...
    'validate_drs_kers:LastKERSSubset', ...
    'The final KERS interval is not a subset of the KERS-on schedule.');

veh = my_params();
assert(isfield(veh,'rho') && isfield(veh,'A'), ...
    'validate_drs_kers:MissingAeroParams', ...
    'veh.rho and veh.A are required by the distance-varying drag model.');
assert(isfield(veh,'Cd_nominal') && isfield(veh,'Cd_drs'), ...
    'validate_drs_kers:MissingDRSParams', ...
    'Cd_nominal and Cd_drs are missing from my_params.m.');
assert(abs(veh.Cd_nominal - 0.9) < 1e-12, ...
    'validate_drs_kers:CdNominal', 'Cd_nominal must be 0.9.');
assert(abs(veh.Cd_drs - 0.8) < 1e-12, ...
    'validate_drs_kers:CdDRS', 'Cd_drs must be 0.8.');
assert(isfinite(veh.rho) && veh.rho > 0 && isfinite(veh.A) && veh.A > 0, ...
    'validate_drs_kers:InvalidAeroParams', ...
    'veh.rho and veh.A must be finite and positive.');

Cd_source = veh.Cd_nominal * ones(size(drs_on));
Cd_source(drs_on == 1) = veh.Cd_drs;
assert(all(Cd_source(drs_on == 0) == veh.Cd_nominal), ...
    'validate_drs_kers:CdWhenDRSOff', ...
    'DRS-off samples must use veh.Cd_nominal.');
assert(all(Cd_source(drs_on == 1) == veh.Cd_drs), ...
    'validate_drs_kers:CdWhenDRSOn', ...
    'DRS-on samples must use veh.Cd_drs.');

assert(isfield(veh,'kers_power_add') && isfield(veh,'kers_power_add_last'), ...
    'validate_drs_kers:MissingKERSParams', ...
    'KERS power parameters are missing from my_params.m.');
assert(isfinite(veh.kers_power_add) && veh.kers_power_add >= 0, ...
    'validate_drs_kers:InvalidKERSPower', ...
    'veh.kers_power_add must be finite and non-negative.');
assert(isfinite(veh.kers_power_add_last) && veh.kers_power_add_last >= 0, ...
    'validate_drs_kers:InvalidLastKERSPower', ...
    'veh.kers_power_add_last must be finite and non-negative.');
assert(abs(veh.kers_power_add - 60e3) < 1e-9, ...
    'validate_drs_kers:DefaultKERSPower', ...
    'The default KERS power-limit addition must be 60e3 W.');

kers_power_add_W = veh.kers_power_add * kers_on + ...
    (veh.kers_power_add_last - veh.kers_power_add) * kers_last_on;
assert(all(kers_power_add_W(kers_on == 0) == 0), ...
    'validate_drs_kers:PowerWhenOff', ...
    'KERS added power must be zero when KERS is off.');
assert(all(kers_power_add_W(kers_on == 1 & kers_last_on == 0) == ...
    veh.kers_power_add), 'validate_drs_kers:EarlierPower', ...
    'Earlier KERS intervals do not use veh.kers_power_add.');
assert(all(kers_power_add_W(kers_last_on == 1) == ...
    veh.kers_power_add_last), 'validate_drs_kers:LastPower', ...
    'Final KERS interval does not use veh.kers_power_add_last.');

% Prefer the audited transition-time interval file for the duration report.
% Fall back to the sampled 1 m data if that file is unavailable.
if isfile(interval_file)
    I = readtable(interval_file);
    required_interval_vars = {'system','duration_s'};
    assert(all(ismember(required_interval_vars, ...
        I.Properties.VariableNames)), ...
        'validate_drs_kers:InvalidIntervalCSV', ...
        'The interval CSV must contain system and duration_s.');
    is_kers = string(I.system) == "KERS";
    kers_duration_s = double(I.duration_s(is_kers));
else
    kers_duration_s = lap_time_s(kers_end) - lap_time_s(kers_start);
end
assert(numel(kers_duration_s) == numel(kers_start), ...
    'validate_drs_kers:KERSDurationCount', ...
    'KERS duration count does not match the detected interval count.');
assert(all(isfinite(kers_duration_s)) && all(kers_duration_s >= 0), ...
    'validate_drs_kers:InvalidKERSDuration', ...
    'KERS interval durations must be finite and non-negative.');

normal_duration_s = sum(kers_duration_s(1:end-1));
last_duration_s = kers_duration_s(end);
max_added_energy_J = veh.kers_power_add * normal_duration_s + ...
    veh.kers_power_add_last * last_duration_s;
fia_energy_limit_J = 400e3;

model_text = fileread('my_model.m');
nlp_text = fileread('my_nlp.m');
oc_text = fileread('my_oc.m');
assert(contains(model_text, ...
    'pv = [kappa; Cd; kers_on; kers_last_on]'), ...
    'validate_drs_kers:PVModel', ...
    'my_model.m does not define the required four-row pv.');
assert(contains(model_text, ...
    'f_drag = 0.5 * veh.rho * Cd * veh.A * ux.^2'), ...
    'validate_drs_kers:DragEquation', ...
    'my_model.m does not use distance-varying Cd in the drag equation.');
assert(contains(nlp_text, ...
    '(veh.kers_power_add_last - veh.kers_power_add) * kers_last_on'), ...
    'validate_drs_kers:PowerConstraint', ...
    'my_nlp.m does not contain the final-interval KERS power selection.');
assert(contains(nlp_text, ...
    'power_motor_available = veh.power_motor_max + kers_power_add_available'), ...
    'validate_drs_kers:TotalAvailablePower', ...
    'my_nlp.m does not add KERS to the existing available-power ceiling.');
assert(contains(nlp_text, ...
    'pv_col = [kappa_col_vec; Cd_col; kers_on_col; kers_last_on_col]'), ...
    'validate_drs_kers:PVCollocation', ...
    'my_nlp.m does not pass the four-row pv at collocation points.');
assert(contains(nlp_text, ...
    'pv_knot = [kappa_knot_vec; Cd_knot; ...'), ...
    'validate_drs_kers:PVKnots', ...
    'my_nlp.m does not pass the four-row pv at knot points.');
assert(contains(oc_text, '''kers_on'',''kers_last_on'''), ...
    'validate_drs_kers:TrackColumns', ...
    'my_oc.m does not add the KERS columns to the track table.');
assert(~contains(nlp_text, ...
    'f_dyn_col(Xkj, Uk_col, Zkj, kappa_col_vec)'), ...
    'validate_drs_kers:OldDynamicsCall', ...
    'An obsolete scalar-kappa mapped dynamics call remains active.');
assert(~contains(nlp_text, ...
    'h_eq_knot(Xk, Uk, Zk, kappa_knot_vec)'), ...
    'validate_drs_kers:OldKnotCall', ...
    'An obsolete scalar-kappa knot path-constraint call remains active.');

fprintf('PASS: DRS/KERS CSV is valid.\n');
fprintf('PASS: 7 DRS intervals and 4 KERS intervals detected.\n');
fprintf('PASS: DRS off/on gives Cd = %.1f / %.1f.\n', ...
    veh.Cd_nominal, veh.Cd_drs);
fprintf('PASS: Earlier KERS addition = %.1f kW.\n', ...
    veh.kers_power_add/1000);
fprintf('PASS: Final KERS addition = %.1f kW (tunable).\n', ...
    veh.kers_power_add_last/1000);
fprintf('Final KERS source interval: %.3f m to %.3f m.\n', ...
    distance_m(kers_start(end)), distance_m(kers_end(end)));
fprintf(['Maximum possible added energy if the optimized drive power ' ...
    'saturates the added ceiling for every extracted KERS-on duration: ' ...
    '%.3f kJ.\n'], max_added_energy_J/1000);
if max_added_energy_J > fia_energy_limit_J + 1e-6
    warning('validate_drs_kers:PotentialEnergyAboveFIALimit', ...
        ['This maximum possible value exceeds 400 kJ. The current OCP ' ...
         'implements only the requested distance-based power ceiling; ' ...
         'it does not enforce a KERS-energy integral. Actual added energy ' ...
         'can be lower because the ceiling need not be saturated.']);
else
    fprintf('PASS: Maximum possible added energy is no more than 400 kJ.\n');
end
fprintf(['PASS: DRS remains connected through Cd, and KERS remains ' ...
    'connected through the four-row pv and power constraint.\n']);
end

function [start_idx, end_idx] = active_intervals(signal)
signal = double(signal(:));
start_idx = find(diff([0; signal]) == 1);
end_idx = find(diff([signal; 0]) == -1);
assert(numel(start_idx) == numel(end_idx), ...
    'validate_drs_kers:MalformedIntervals', ...
    'Binary active-state intervals are malformed.');
end
