clear
close all
clc

addpath('C:\casadi_test\vehicle_model')

addpath('C:\casadi_test\track_data')
load OmegaB
load nl
load nr
load h_vec
load S_all_points
load P_L
load P_R
load C_true_project
load Theta

delta_x_from_GE = 0;
delta_y_from_GE = 0;
angle_to_rotate_in_rad = 0;
% load origin

nl_for_sim = nl * (-1);
nr_for_sim = nr * (-1);

%%
nx = 8; % 6
nu = 6; % 8
% nmesh = 4684*1; % 4684*1
nmesh = 5452*2; % 5452*1
sa = 3; % % number of collocation points per interval, do not change this!

ninterval = nmesh-1;
n_all_collocation_points = sa * ninterval;

%% Load Visual Studio generated files

VS_FolderName = 'C:\Users\John 117\Documents\Visual Studio 2022\Projects\Casadi_test\Casadi_test\Output_files';

% Read objective_value_opt_from_IPOPT generated by Visual Studio
FileName1_VS   = 'objective_value_opt_from_IPOPT.txt';
File1_VS       = fullfile(VS_FolderName, FileName1_VS);
objective_value_opt_from_IPOPT = load(File1_VS);

% Read x_opt_from_IPOPT generated by Visual Studio
FileName2_VS   = 'x_opt_from_IPOPT.txt';
File2_VS       = fullfile(VS_FolderName, FileName2_VS);
x_opt_from_IPOPT = load(File2_VS);

%%
% uncomment this following code to plot with physical units
load z_lb_ub_from_Matlab
z_opt = (z_lb_ub_from_Matlab(:,2) - z_lb_ub_from_Matlab(:, 1)) .* x_opt_from_IPOPT + z_lb_ub_from_Matlab(:, 1);
x_opt_from_IPOPT = z_opt;

Z_bar = NaN(length(x_opt_from_IPOPT)+nu, 1);

Z_bar(1:nx) = x_opt_from_IPOPT(1:nx);
Z_bar(nx+1:nx+nu) = 0; % dummy u's at t1
Z_bar(nx+nu+1:end) = x_opt_from_IPOPT(nx+1:end);

%%
first_zero_matrix = sparse(nx*(ninterval)*sa, nx+nu);
first_unit_matrix = speye((ninterval)*sa);
second_zero_matrix = sparse(nx, nu);
second_unit_matrix = speye(nx);
Kproduct_matrix = kron(first_unit_matrix, [second_unit_matrix, second_zero_matrix]);

% E_Xbar
E_Xbar = [first_zero_matrix, Kproduct_matrix];

%%
X_bar = E_Xbar * Z_bar;

X_bar_reshaped = reshape(X_bar, nx, []);

X_all_table = NaN(nx, n_all_collocation_points+1);
X_all_table(:, 1) = x_opt_from_IPOPT(1:nx);
X_all_table(:, 2:end) = X_bar_reshaped;

%%
% Assuming your column vector is called `vec`
block_size = nu;       % rows 6–13 = 8 elements
stride = nx+nu;           % rows between starts of consecutive blocks
first_idx = nx+1;         % starting index of the first block

% Compute number of blocks that fit within the vector
max_k = floor((length(Z_bar) - first_idx + 1) / stride);

% Preallocate
extracted_blocks = zeros(block_size, max_k);

% Loop over each block
for k = 1:max_k
    start_idx = first_idx + (k-1) * stride;
    extracted_blocks(:, k) = Z_bar(start_idx : start_idx + block_size - 1);
end

%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% ToDo: double check
U_all_table = [extracted_blocks, Z_bar(length(Z_bar)-nu+1:end)]; % 182643   196693    228949
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Recompute vehicle model

Ucar     = X_all_table(1, :);
V        = X_all_table(2, :);
yr       = X_all_table(3, :);
ks       = X_all_table(4, :);
nn       = X_all_table(5, :);
Fx_tires = X_all_table(6, :);
Fy_tires = X_all_table(7, :);
Pkers    = X_all_table(8, :);

k_FL     = U_all_table(1, :);
k_FR     = U_all_table(2, :);
k_RL     = U_all_table(3, :);
k_RR     = U_all_table(4, :);
deta_ST  = U_all_table(5, :);
u_Pkers  = U_all_table(6, :);

%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
curvature_vec = OmegaB(1:end, 3);
curvature_vec = curvature_vec * (-1);
curv_input = curvature_vec.';
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Define parameters

% environement
gravity = 9.8; % m*s^(-2)
rou_air = 1.2; % kg*m^(-3)

% tire
Fz1 = 2000; % N
Fz2 = 6000; % N
mu_x_max1 = 1.1;
mu_x_max2 = 1.0;
k_max1 = 0.105;
k_max2 = 0.095;
mu_y_max1 = 1.15;
mu_y_max2 = 1.05;
alpha_max1 = 6.5; % deg
alpha_max2 = 6.0; % deg
Qx = 1.9;
Qy = 1.9;
rou_correction1 = 10^(-5);
rou_correction2 = 10^(-5);
dGrip = 0; % 0 default

% vehicle
mass = 2635; % kg vehicle mass  2555 - 2715
wb = 3.105; % m wheel base  3.105
Iz = 0.3 * mass * wb^2; % kg*m^2 yaw inertia
acom = 0.51*wb; % m distance between center of mass and front axle
bcom = wb - acom; % m distance between center of mass and rear axle
hcom = 0.63; % m height of center of mass to ground
dr = 0.5; % roll moment distribution (fraction at the front)
twF_h = 1.716/2; % m front-wheel to car-centre-line distance
twR_h = 1.727/2; % m rear-wheel to car-centre-line distance
td_FL = 0.745; % m front left wheel diameter
td_FR = 0.745; % m front right wheel diameter
td_RL = 0.769; % m rear left wheel diameter
td_RR = 0.769; % m rear right wheel diameter
% aero
S_front = 3.05; % m^2 air front area
CdA = 2 * 227*10^3 / (rou_air * (200/3.6)^3) / S_front;
ClA = CdA * 0.05;
acop = acom + 0.1; % m distance between center of pressure and front axle
hcop = 0.6; % m distance between center of pressure and ground
% differential
Kd = 1.5; % N*m*s*rad^(-1)


%% Calculate

% aero
[Fdrag, Fdown] = aero(Ucar, rou_air, S_front, CdA, ClA);

% wheel kinematics
[U_FL, U_FR, U_RL, U_RR, w_FL, w_FR, w_RL, w_RR, V_FL, V_FR, V_RL, V_RR, alpha_FL, alpha_FR, alpha_RL, alpha_RR] = wheel_kinematics(Ucar, V, yr, k_FL, k_FR, k_RL, k_RR, deta_ST, twF_h, twR_h, acom, bcom, td_FL, td_FR, td_RL, td_RR);

% wheel load
[Fz_FL, Fz_FR, Fz_RL, Fz_RR] = wheel_load(Fx_tires, Fy_tires, Fdown, Fdrag, bcom, mass, gravity, hcom, hcop, acop, acom, dr, twF_h, twR_h);

% tire force
[Fx_FL, Fy_FL] = tire_force(k_FL, alpha_FL, Fz_FL, Fz1, Fz2, mu_x_max1, mu_x_max2, mu_y_max1, mu_y_max2, k_max1, k_max2, alpha_max1, alpha_max2, Qx, Qy, rou_correction1, rou_correction2, dGrip);
[Fx_FR, Fy_FR] = tire_force(k_FR, alpha_FR, Fz_FR, Fz1, Fz2, mu_x_max1, mu_x_max2, mu_y_max1, mu_y_max2, k_max1, k_max2, alpha_max1, alpha_max2, Qx, Qy, rou_correction1, rou_correction2, dGrip);
[Fx_RL, Fy_RL] = tire_force(k_RL, alpha_RL, Fz_RL, Fz1, Fz2, mu_x_max1, mu_x_max2, mu_y_max1, mu_y_max2, k_max1, k_max2, alpha_max1, alpha_max2, Qx, Qy, rou_correction1, rou_correction2, dGrip);
[Fx_RR, Fy_RR] = tire_force(k_RR, alpha_RR, Fz_RR, Fz1, Fz2, mu_x_max1, mu_x_max2, mu_y_max1, mu_y_max2, k_max1, k_max2, alpha_max1, alpha_max2, Qx, Qy, rou_correction1, rou_correction2, dGrip);

% evaluate ODEs' rhs
[f1, f2, f3, f4, f5, f6, f7, f8] = ODEs_rhs(Ucar, V, yr, ks, nn, k_FL, k_FR, k_RL, k_RR, deta_ST, Fx_tires, Fy_tires, u_Pkers, Fx_FL, Fx_FR, Fx_RL, Fx_RR, Fy_FL, Fy_FR, Fy_RL, Fy_RR, Fdrag, curv_input, mass, Iz, acom, bcom, twF_h, twR_h);

% evaluate path constraints body

Pm = (  (Fx_RL + Fx_RR) .* Ucar  );

g5  = Pm - Pkers;


%% Compute racing line

% Compute unit vector PR_PL
vector_P_R_P_L = P_L - P_R;
unit_vector_P_R_P_L = vector_P_R_P_L ./ vecnorm(vector_P_R_P_L, 2, 2);

% coordinates of racing line
racing_line_coordinates = C_true_project + unit_vector_P_R_P_L .* (-nn).';

%% Compute car's yaw angle wrt. Earth

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% car_yaw_angle_in_deg = rad2deg(Theta + ks.');
car_yaw_angle_in_deg = rad2deg(Theta - ks.');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% Compute coordinates of the center of the front left wheel

% angle between the car center line and the line connecting car geometric
% center and the center of the front left wheel
angle_AGC = atan2(twF_h, acom); % [rad]

% distance between the car geometric center and the center of the front
% left wheel
AG = (twF_h^2 + acom^2)^0.5; % [m]

for index_car_yaw_angle_in_deg = 1: length(car_yaw_angle_in_deg)

    x_y_FL_temp = [cos(angle_AGC), -sin(angle_AGC); sin(angle_AGC), cos(angle_AGC)] * [cos(deg2rad(car_yaw_angle_in_deg(index_car_yaw_angle_in_deg))), -sin(deg2rad(car_yaw_angle_in_deg(index_car_yaw_angle_in_deg))); sin(deg2rad(car_yaw_angle_in_deg(index_car_yaw_angle_in_deg))), cos(deg2rad(car_yaw_angle_in_deg(index_car_yaw_angle_in_deg)))] * [1;0] * AG;

    x_FL(index_car_yaw_angle_in_deg, 1) = racing_line_coordinates(index_car_yaw_angle_in_deg, 1) + x_y_FL_temp(1);
    y_FL(index_car_yaw_angle_in_deg, 1) = racing_line_coordinates(index_car_yaw_angle_in_deg, 2) + x_y_FL_temp(2);

end

%% Compute coordinate of the center of the front right wheel

% angle between the car center line and the line connecting car geometric
% center and the center of the front left wheel
angle_BGC = atan2(twF_h, acom); % [rad]

% distance between the car geometric center and the center of the front
% left wheel
BG = (twF_h^2 + acom^2)^0.5; % [m]

for index_car_yaw_angle_in_deg = 1: length(car_yaw_angle_in_deg)

    x_y_FR_temp = [cos(-angle_BGC), -sin(-angle_BGC); sin(-angle_BGC), cos(-angle_BGC)] * [cos(deg2rad(car_yaw_angle_in_deg(index_car_yaw_angle_in_deg))), -sin(deg2rad(car_yaw_angle_in_deg(index_car_yaw_angle_in_deg))); sin(deg2rad(car_yaw_angle_in_deg(index_car_yaw_angle_in_deg))), cos(deg2rad(car_yaw_angle_in_deg(index_car_yaw_angle_in_deg)))] * [1;0] * BG;

    x_FR(index_car_yaw_angle_in_deg, 1) = racing_line_coordinates(index_car_yaw_angle_in_deg, 1) + x_y_FR_temp(1);
    y_FR(index_car_yaw_angle_in_deg, 1) = racing_line_coordinates(index_car_yaw_angle_in_deg, 2) + x_y_FR_temp(2);

end

%% Compute the yaw angle of the front left wheel with respect to Earth

% ST_yaw_angle_in_deg = car_yaw_angle_in_deg - rad2deg(deta_ST.'); % this was used for GE
ST_yaw_angle_in_deg = 0 - rad2deg(deta_ST.');

%% States

figure()
plot(S_all_points, Ucar, '-')
hold on
plot(S_all_points, V, '-')
xlabel('Distance, m')

figure();plot(S_all_points, yr, '-');xlabel('Distance, m')
figure();plot(S_all_points, ks, '-');xlabel('Distance, m')

figure()
plot(S_all_points, nn, '-')
hold on
plot(S_all_points, nl_for_sim + 0.73)
hold on
plot(S_all_points, nr_for_sim - 0.73)
xlabel('Distance, m')

figure()
plot(S_all_points, Fx_tires, '-')
hold on
plot(S_all_points, Fy_tires, '-')
xlabel('Distance, m')
legend('Fx\_tires', 'Fy\_tires')
title('Fx\_tires and Fy\_tires')

figure();plot(S_all_points, Pkers, '-');xlabel('Distance, m');title('Pkers')

figure()
plot(S_all_points, Pm)
hold on
plot(S_all_points, Pkers, '-')
xlabel('Distance, m')
legend('Pm W', 'Pkers, W')
title('Pm', 'Pkers')

%% Controls

figure()
plot(S_all_points, k_FL, '-')
hold on
plot(S_all_points, k_FR, '-')
xlabel('Distance, m')

figure()
plot(S_all_points, k_RL, '-')
hold on
plot(S_all_points, k_RR, '-')
xlabel('Distance, m')
legend('k\_RL', 'k\_RR')

figure()
plot(S_all_points, deta_ST, '-')
xlabel('Distance, m')

figure()
plot(S_all_points, u_Pkers, '-')
xlabel('Distance, m')
legend('u\_Pkers')
title('u\_Pkers')

%% Path constraints and so on

% figure()
% semilogy(S_all_points, abs(g1))
% hold on
% semilogy(S_all_points, abs(g2))
% hold on
% semilogy(S_all_points, abs(g3))
% hold on
% semilogy(S_all_points, abs(g4))
% xlabel('Distance, m')
% legend('g1', 'g2', 'g3', 'g4')

% figure()
% plot(S_all_points, g3)
% xlabel('Distance, m')
% title('g3')

figure()
plot(S_all_points, g5)
xlabel('Distance, m')
title('g5')

figure()
plot(S_all_points, Fx_RL)
hold on
plot(S_all_points, Fx_RR)
xlabel('Distance, m')
legend('Fx\_RL', 'Fx\_RR')
title('Fx\_RL and Fx\_RR')

%% Racing line

figure()
plot3(P_L(:,1), P_L(:,2), P_L(:,3)*0, '-k')
hold on
plot3(P_R(:,1), P_R(:,2), P_R(:,3)*0, '-k')
hold on
plot3(P_L(:,1), P_L(:,2), P_L(:,3)-min(P_L(:,3)), '-r')
hold on
plot3(P_R(:,1), P_R(:,2), P_R(:,3)-min(P_R(:,3)), '-b')
hold on
plot3(racing_line_coordinates(:,1), racing_line_coordinates(:,2), racing_line_coordinates(:,3)-min(racing_line_coordinates(:,3)), '-g')
hold on
% plot3(C_true_project(:,1), C_true_project(:,2), C_true_project(:,3), '-g')
% title('Processed 3D track with lowest elevation 0m, with racing line')
axis equal; grid on;

% debug = 1;

%% Car's yaw angle wrt. Earth

figure()
plot(S_all_points, car_yaw_angle_in_deg)
xlabel('Distance, m')
title('Car yaw angle in deg wrt. Earth')

%% Check whether the distance between the geometric center of the car and the center of the front wheel is the same as AG.

check_distance = (  (racing_line_coordinates(:,1) - x_FL).^2  +   (racing_line_coordinates(:,2) - y_FL).^2  ).^0.5;
figure()
plot(check_distance - AG)
xlabel('Data index')
title('Check distance diff FL')

%% Check whether the distance between the geometric center of the car and the center of the front right wheel is the same as BG.

check_distance_BG = (  (racing_line_coordinates(:,1) - x_FR).^2  +   (racing_line_coordinates(:,2) - y_FR).^2  ).^0.5;
figure()
plot(check_distance_BG - BG)
xlabel('Data index')
title('Check distance diff FR')

%% Plot racing line, FL line and FR line

% --- Inputs assumed available ---
% P_L, P_R                          : [N x 2]
% racing_line_coordinates           : [N x 2]
% x_FL, y_FL, x_FR, y_FR            : [N x 1] or [1 x N]
% car_yaw_angle_in_deg              : [N x 1] (degrees)
% ST_yaw_angle_in_deg               : [N x 1] (degrees)

% --- Base plots ---
figure()
plot(P_L(:,1), P_L(:,2), '-k'); hold on
plot(P_R(:,1), P_R(:,2), '-k');
plot(racing_line_coordinates(:,1), racing_line_coordinates(:,2), '-or');
plot(x_FL, y_FL, '-ob');
plot(x_FR, y_FR, '-og');

% --- Ensure column vectors & consistent lengths ---
x_FL = x_FL(:);  y_FL = y_FL(:);
x_FR = x_FR(:);  y_FR = y_FR(:);
car_yaw_angle_in_deg = car_yaw_angle_in_deg(:);
ST_yaw_angle_in_deg  = ST_yaw_angle_in_deg(:);

N = size(racing_line_coordinates, 1);
assert(all([numel(x_FL), numel(y_FL), numel(x_FR), numel(y_FR), ...
            numel(car_yaw_angle_in_deg), numel(ST_yaw_angle_in_deg)] == N), ...
    'All vectors must match racing_line_coordinates length.');

% --- Sampling (use one set of indices everywhere) ---
k = 20;                     % increase k → fewer connectors/arrows
idx = 1:k:N;

% --- Sampled connectors from racing line to FL/FR ---
line([racing_line_coordinates(idx,1), x_FL(idx)]', ...
     [racing_line_coordinates(idx,2), y_FL(idx)]', ...
     'Color', [0 0 1], 'LineWidth', 0.5);   % blue

line([racing_line_coordinates(idx,1), x_FR(idx)]', ...
     [racing_line_coordinates(idx,2), y_FR(idx)]', ...
     'Color', [0 0.5 0], 'LineWidth', 0.5); % green

% --- Yaw arrows at racing line (car_yaw_angle_in_deg) ---
L_car = 2;  % arrow length in your plot units
dx_car = L_car * cosd(car_yaw_angle_in_deg(idx));
dy_car = L_car * sind(car_yaw_angle_in_deg(idx));

quiver(racing_line_coordinates(idx,1), ...
       racing_line_coordinates(idx,2), ...
       dx_car, dy_car, ...
       'AutoScale','off', 'Color','m', 'LineWidth',1, 'MaxHeadSize',1);

% --- ST yaw arrows centered at FL/FR (ST_yaw_angle_in_deg) ---
L_st = 1.5;  % arrow length for ST yaw (adjust as needed)
ux = L_st * cosd(ST_yaw_angle_in_deg(idx));
uy = L_st * sind(ST_yaw_angle_in_deg(idx));

% Center the arrows at each point: start at (x - ux/2, y - uy/2)
% FL arrows
quiver(x_FL(idx) - ux/2, ...
       y_FL(idx) - uy/2, ...
       ux, uy, ...
       'AutoScale','off', 'Color',[0 0.6 1], 'LineWidth',1, 'MaxHeadSize',1);

% FR arrows
quiver(x_FR(idx) - ux/2, ...
       y_FR(idx) - uy/2, ...
       ux, uy, ...
       'AutoScale','off', 'Color',[1 0.6 0], 'LineWidth',1, 'MaxHeadSize',1);

axis equal; grid on
title('Track, connectors, and yaw vectors')
legend({'Left boundary','Right boundary','Racing line','FL trace','FR trace'}, ...
       'Location','bestoutside')

%% Plot the yaw angle of the FL wheel wrt. Earth

figure()
plot(S_all_points, ST_yaw_angle_in_deg)
xlabel('Distance, m')
title('ST\_yaw\_angle\_in\_deg')

%% save

cd('C:\casadi_test\data_for_Blender')

ks = ks.';
% save('ideal_racing_line_from_OC', 'racing_line_coordinates', 'x_FL', 'y_FL', 'x_FR', 'y_FR', 'delta_x_from_GE', 'delta_y_from_GE', 'angle_to_rotate_in_rad', 'P_R', 'P_L', 'ks', 'Theta');
% save('car_yaw_angle_in_deg', 'car_yaw_angle_in_deg');
% save('ST_yaw_angle_in_deg', 'ST_yaw_angle_in_deg');

%% form the time trajectory

% calculate car's magnitude of the ground velocity along the track s coordinates
ground_velocity_along_s = (  Ucar.^2 + V.^2  ).^(0.5); % [m/s]
ground_velocity_along_s = ground_velocity_along_s.';

% z_nlp without the nx states at time t1
z_nlp_except_at_t1 = z_opt(nx+1:end, 1);
z_nlp_except_at_t1_table = reshape(z_nlp_except_at_t1, (nx+nu), sa*(ninterval));

a31 = (16-(6^0.5)) / 36;
a32 = (16+(6^0.5)) / 36;
a33 = 1/9;
b_vec = [a31, a32, a33];

% integrand_vec is the integrand evaluated at all collocation points
integrand_vec = zeros(n_all_collocation_points, 1);
for index_collocation_points = 1:n_all_collocation_points
    
    curv_at_this_collocation_point = curvature_vec(index_collocation_points);
    
    xu_val_k = z_nlp_except_at_t1_table(:, index_collocation_points);
    
    x_vec_val_k = xu_val_k(1:nx);
    u_vec_val_k = xu_val_k(nx+1 : end);

    integrand_val_k = obj_integrand(x_vec_val_k, u_vec_val_k, curv_at_this_collocation_point);

    integrand_vec(index_collocation_points) = integrand_val_k;
end

% compute objective function value
integrand_table = reshape(integrand_vec, sa, (ninterval));

ninterval_temp = 1;
for index_ninteral = 1:ninterval

    integral_value_from_Matlab = 0; % initialization
    for index_interval = 1:ninterval_temp
        
        integral_value_from_Matlab = integral_value_from_Matlab + h_vec(index_interval)*b_vec*integrand_table(:, index_interval);
        
    end
    
    integral_value_from_Matlab_vec(index_ninteral) = integral_value_from_Matlab;
    
    ninterval_temp = ninterval_temp + 1;

end

S_mesh_points = [0; cumsum(h_vec).'];

time_info = interp1(S_mesh_points, [0;integral_value_from_Matlab_vec.'], S_all_points);

figure()
plot(S_all_points, time_info)
xlabel('Distance, m')
title('time\_info')

% save('time_info', 'time_info', 'ground_velocity_along_s')



%% calculate each wheel's rotation angle

% front left wheel rotatoin angle trajectory
rotation_angle_FL_in_rad = cumtrapz(time_info, w_FL);
rotation_angle_FL_in_deg = rad2deg(rotation_angle_FL_in_rad.');

% front right wheel rotatoin angle trajectory
rotation_angle_FR_in_rad = cumtrapz(time_info, w_FR);
rotation_angle_FR_in_deg = rad2deg(rotation_angle_FR_in_rad.');

figure()
plot(time_info, rotation_angle_FL_in_deg)
hold on
plot(time_info, rotation_angle_FR_in_deg)
legend('FL', 'FR')
ylabel('Wheel rotation angle in [deg]')

% put the rotation_angle_FL_in_deg and rotation_angle_FR_in_deg in the
% range [-180, 180] deg, this is required by Google Earth pro
rotation_angle_FL_in_deg_wrapped = wrapTo180(rotation_angle_FL_in_deg);
rotation_angle_FR_in_deg_wrapped = wrapTo180(rotation_angle_FR_in_deg);

figure()
plot(time_info, rotation_angle_FL_in_deg_wrapped)
hold on
plot(time_info, rotation_angle_FR_in_deg_wrapped)
legend('FL', 'FR')
ylabel('Wheel rotation angle wrapped in [deg]')

%save
% save('FL_FR_rotation_angles_in_deg', 'rotation_angle_FL_in_deg_wrapped', 'rotation_angle_FR_in_deg_wrapped')



%% cut some part of the trajectory for Blender debug
% 
% % cut_start = 9913; % from here left wheel is higher
% % cut_end = cut_start + 100;
% 
% % cut_end = 13808;
% 
% % cut_start = 3524;
% % cut_end = 4359;
% 
% % cut_start = 8188; %from here right wheel is higher
% % cut_end = 8998;
% 
% % cut_start = 8188; %from here right wheel is higher
% % cut_end = 9913 + 1;
% 
% cut_start = 8188;
% cut_end = 9913;
% 
% % % test wheel wobble
% % cut_start = 8188;
% % cut_end = cut_start + 700;
% 
% racing_line_coordinates = racing_line_coordinates(cut_start:cut_end, :);
% time_info = time_info(cut_start:cut_end, :);
% ground_velocity_along_s = ground_velocity_along_s(cut_start:cut_end, :);
% rotation_angle_FL_in_deg_wrapped = rotation_angle_FL_in_deg_wrapped(cut_start:cut_end, :);
% rotation_angle_FR_in_deg_wrapped = rotation_angle_FR_in_deg_wrapped(cut_start:cut_end, :);
% ST_yaw_angle_in_deg = ST_yaw_angle_in_deg(cut_start:cut_end, :);
% 
% rotation_angle_FL_in_deg = rotation_angle_FL_in_deg(cut_start:cut_end, :);
% rotation_angle_FR_in_deg = rotation_angle_FR_in_deg(cut_start:cut_end, :);


%% Write to .csv files for Blender to render video

filename = 'racing_line_coordinates.csv';
% Open file
fid = fopen(filename, 'w');
% Write header
fprintf(fid, 'x,y,z\n');
% Write data with full precision
% %.15g gives ~15 significant digits (full double precision)
fprintf(fid, '%.15g,%.15g,%.15g\n', racing_line_coordinates.');
fclose(fid);
disp(['Saved with headers to ', filename]);

filename1 = 'time_info.csv';
fid1 = fopen(filename1, 'w');
fprintf(fid1, 't\n');
fprintf(fid1, '%.15g\n', time_info.');
fclose(fid1);
disp(['Saved with headers to ', filename1]);

filename2 = 'ground_velocity_along_s.csv';
fid2 = fopen(filename2, 'w');
fprintf(fid2, 'u\n');
fprintf(fid2, '%.15g\n', ground_velocity_along_s.');
fclose(fid2);
disp(['Saved with headers to ', filename2]);

filename3 = 'rotation_angle_FL_in_deg_wrapped.csv';
fid3 = fopen(filename3, 'w');
fprintf(fid3, 'rFL\n');
fprintf(fid3, '%.15g\n', rotation_angle_FL_in_deg_wrapped.');
fclose(fid3);
disp(['Saved with headers to ', filename3]);

filename4 = 'rotation_angle_FR_in_deg_wrapped.csv';
fid4 = fopen(filename4, 'w');
fprintf(fid4, 'rFR\n');
fprintf(fid4, '%.15g\n', rotation_angle_FR_in_deg_wrapped.');
fclose(fid4);
disp(['Saved with headers to ', filename4]);

filename5 = 'ST_yaw_angle_in_deg.csv';
fid5 = fopen(filename5, 'w');
fprintf(fid5, 'st\n');
fprintf(fid5, '%.15g\n', ST_yaw_angle_in_deg.');
fclose(fid5);
disp(['Saved with headers to ', filename5]);

filename6 = 'rotation_angle_FL_in_deg.csv';
fid6 = fopen(filename6, 'w');
fprintf(fid6, 'rFL\n');
fprintf(fid6, '%.15g\n', rotation_angle_FL_in_deg.');
fclose(fid6);
disp(['Saved with headers to ', filename6]);

filename7 = 'rotation_angle_FR_in_deg.csv';
fid7 = fopen(filename7, 'w');
fprintf(fid7, 'rFR\n');
fprintf(fid7, '%.15g\n', rotation_angle_FR_in_deg.');
fclose(fid7);
disp(['Saved with headers to ', filename7]);
