clear
close all
clc

%% 
edgeloop00 = importfile("C:\Users\John 117\Documents\Blender Projects\edge_export\edge_loop_00.csv");
edgeloop01 = importfile("C:\Users\John 117\Documents\Blender Projects\edge_export\edge_loop_01.csv");

%% Flip edgeloop01 data sequence to the direction of car moving
edgeloop01 = flip(edgeloop01);

%%
figure()
plot3(edgeloop00(:,1), edgeloop00(:,2), edgeloop00(:,3), '-o')
hold on
plot3(edgeloop01(:,1), edgeloop01(:,2), edgeloop01(:,3), '-o')
legend('edgeloop00', 'edgeloop01')
axis equal
grid minor


%% Delete some non-smooth section of data
cut = [158:161, 195:198, 211:214, 223:235, 550:552, 914:915, 957:959, 1185:1186, 1483:1486, 2305];

edgeloop01(cut, :) = [];



%% Arrange the data from the SF line

% these two points are the two end points of the SF line of the track,
% which I measured from the track 3D model in Blender

% Define two points
x1_SF = 100.0956; y1_SF = -323.4547; z1_SF = (-3.06471-3.06041)/2;
x2_SF = 102.8964637; y2_SF = -336.783202595; z2_SF = (-3.25742-3.25772)/2;





%%
% Make vectors
X = [x1_SF, x2_SF];
Y = [y1_SF, y2_SF];
Z = [z1_SF, z2_SF];


figure()
plot3(edgeloop00(:,1), edgeloop00(:,2), edgeloop00(:,3), '-o')
hold on
plot3(edgeloop01(:,1), edgeloop01(:,2), edgeloop01(:,3), '-o')
hold on
plot(X, Y, '-r', 'LineWidth', 2);  % red line
hold on;
plot(X, Y, 'ob', 'MarkerSize', 8, 'MarkerFaceColor', 'b');
legend('edgeloop00', 'edgeloop01')
axis equal
grid minor



%% Put the first point of edgeloop00 to the first row

aa = 72;
bb = 110;

edgeloop00_temp = nan(length(edgeloop00(:, 1)), 3);
edgeloop00_temp(1:size(edgeloop00(aa:end, 3)), :) = edgeloop00(aa:end, :);
edgeloop00_temp(size(edgeloop00(aa:end, 3))+1:end, :) = edgeloop00(1:(aa-1), :);

edgeloop01_temp = nan(length(edgeloop01(:, 1)), 3);
edgeloop01_temp(1:size(edgeloop01(bb:end, 3)), :) = edgeloop01(bb:end, :);
edgeloop01_temp(size(edgeloop01(bb:end, 3))+1:end, :) = edgeloop01(1:(bb-1), :);


%%
edgeloop00 = edgeloop00_temp;
edgeloop01 = edgeloop01_temp;



%% Formulate coordinates so that the first and last points is at the SF line

edgeloop00_new = nan(length(edgeloop00(:,1)) + 2, 3);
edgeloop01_new = nan(length(edgeloop01(:,1)) + 2, 3);

edgeloop00_new(1, :) = [x2_SF, y2_SF, z2_SF];
edgeloop00_new(end, :) = edgeloop00_new(1, :);

edgeloop01_new(1, :) = [x1_SF, y1_SF, z1_SF];
edgeloop01_new(end, :) = edgeloop01_new(1, :);

edgeloop00_new(2:end-1, :) = edgeloop00;
edgeloop01_new(2:end-1, :) = edgeloop01;


%%
edgeloop00 = edgeloop00_new;
edgeloop01 = edgeloop01_new;


%%
% figure()
% plot3(edgeloop00(:,1), edgeloop00(:,2), edgeloop00(:,3), '-o')
% hold on
% plot3(edgeloop01(:,1), edgeloop01(:,2), edgeloop01(:,3), '-o')
% legend('edgeloop00', 'edgeloop01')
% axis equal
% grid minor

figure()
plot(edgeloop00(:,1), edgeloop00(:,2), '-o')
hold on
plot(edgeloop01(:,1), edgeloop01(:,2), '-o')
legend('edgeloop00', 'edgeloop01')
axis equal
grid minor



% Your variable: edgeloop00 (N x 3 double)
filename = 'edgeloop00_toprocess.csv';
filename1 = 'edgeloop01_toprocess.csv';

% Open file
fid = fopen(filename, 'w');
fid1 = fopen(filename1, 'w');

% Write header
fprintf(fid, 'x,y,z\n');
fprintf(fid1, 'x,y,z\n');

% Write data with full precision
% %.15g gives ~15 significant digits (full double precision)
fprintf(fid, '%.15g,%.15g,%.15g\n', edgeloop00.');
fprintf(fid1, '%.15g,%.15g,%.15g\n', edgeloop01.');

% Close file
fclose(fid);
fclose(fid1);

disp(['Saved with headers to ', filename]);
disp(['Saved with headers to ', filename1]);






debug = 1;









function edgeloop00 = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  EDGELOOP00 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the numeric data.
%
%  EDGELOOP00 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  edgeloop00 = importfile("C:\Users\John 117\Documents\Blender Projects\edge_export\edge_loop_00.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Aug-2025 10:22:56

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["x", "y", "z"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
edgeloop00 = readtable(filename, opts);

%% Convert to output type
edgeloop00 = table2array(edgeloop00);
end
